services:
  workspace:
    build:
      context: .
    volumes:
      - .:/workspaces/crx-pixiv-illust-meta:cached
      - node_modules:/workspaces/crx-pixiv-illust-meta/node_modules
    tty: true
    init: true

volumes:
  node_modules:
