name: CI

on:
  push:
    branches:
      # SEE: https://stackoverflow.com/a/57903434
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read node version from Dockerfile
        run: echo ::set-output name=node_version::$(grep -P -o '(?<=node:)[0-9]+\.[0-9]+\.[0-9]+' Dockerfile)
        id: node_version

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test -- --coverage --reporter=default --reporter=junit --outputFile=test-results.xml

      - name: Output test summary
        uses: test-summary/action@v1
        with:
          paths: 'test-results.xml'
        if: always()

      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          output: file
          badge: true
          format: markdown
        if: always()

      - name: Output coverage summary
        run: |
          echo '---' >> $GITHUB_STEP_SUMMARY
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        if: always()

      - name: Run build
        run: npm run build
