name: CI

on:
  push:
    branches:
      # SEE: https://stackoverflow.com/a/57903434
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn
      - run: yarn install --no-progress --frozen-lockfile --network-timeout 600000
      - run: yarn lint
      - run: yarn test
      - run: yarn build
