name: CI

on:
  push:
    branches:
      # SEE: https://stackoverflow.com/a/57903434
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run linter
        run: pnpm lint

  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: pnpm test -- --coverage

      - name: Output test summary
        uses: test-summary/action@v1
        with:
          paths: tests/results/results.xml
        if: always()

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          vite-config-path: vite.config.ts
        if: always()

  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run build
        run: pnpm build
