name: Release

on:
  push:
    tags:
      - '*'

env:
  archive_basename_prefix: chrome-pixiv-bookmark-rate-ext

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2.3.0

      - name: Compute archive basename
        id: context
        run: echo ::set-output name=archive_basename::${{ env.archive_basename_prefix }}-${{ steps.get_version.outputs.version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Copy license file
        run: cp LICENSE.md dist

      - name: Rename directory for archive
        run: mv dist ${{ steps.context.outputs.archive_basename }}

      - name: Make tarball
        uses: TheDoctor0/zip-release@0.6.2
        with:
          path: ${{ steps.context.outputs.archive_basename }}
          type: tar
          filename: ${{ steps.context.outputs.archive_basename }}.tar.gz

      - name: Make zipball
        uses: TheDoctor0/zip-release@0.6.2
        with:
          path: ${{ steps.context.outputs.archive_basename }}
          type: zip
          filename: ${{ steps.context.outputs.archive_basename }}.zip

      - name: Create release draft
        uses: ncipollo/release-action@v1.10.0
        with:
          name: ${{ steps.get_version.outputs.version }}
          prerelease: ${{ steps.get_version.outputs.isPrerelease }}
          draft: true
          artifacts: '${{ steps.context.outputs.archive_basename }}.*'
          token: ${{ secrets.GITHUB_TOKEN }}
